config/routes.rb
Olive::Application.routes.draw do
  resources :links do
    post :sort, on: :collection
  end

  resources :pages do
    get :manage, on: :member
    post :sort, on: :collection
    resources :sections do
      post :sort, on: :collection
    end
  end

  root :to => 'pages#home'
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :title, :location

  validates_presence_of :title, :location
  validates :position, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  default_scope order: :position

  before_validation :set_initial_position
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :title, :text, :image, :page_id

  belongs_to :page
  has_many :pages
  has_many :sections, dependent: :destroy

  validates_presence_of :title
  validates :position, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  default_scope order: :position

  before_validation :set_initial_position

  has_attached_file :image, styles: { thumb: '100x100#', small: '240x240>' }

  def to_param
    "#{self.id}-#{self.title.parameterize if self.title}"
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :title, :text, :section_image

  belongs_to :page

  validates_presence_of :page, :text
  validates :position, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  default_scope order: :position

  before_validation :set_initial_position

  has_attached_file :section_image, styles: { thumb: '100x100#', small: '240x240>' }
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :find_pages
  before_filter :find_site
  before_filter :find_links

  private
  def find_page
    @page = Page.find(params[:page_id] || params[:id])
  end

  def find_pages
    @pages = Page.all
  end

  def find_links
    @links = Link.all
  end

  def find_site
    @site = Site.first
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :find_link, only: [:edit, :update, :destroy]
  http_basic_authenticate_with name: 'foo', password: 'bar'

  def new
    @link = Link.new
  end

  # def edit

  def create
    @link = Link.new(params[:link])

    if @link.save
      redirect_to root_path, notice: 'Link was successfully created.'
    else
      render action: :new
    end
  end

  def update
    if @link.update_attributes(params[:link])
      redirect_to root_path, notice: 'Link was successfully updated.'
    else
      render action: :edit
    end
  end

  def destroy
    @link.destroy

    redirect_to root_path
  end

  def sort
    Link.all.each do |link|
      link.position = params['link'].index(link.id.to_s)
      link.save
    end
    render nothing: true
  end

  private
  def find_link
    @link = Link.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :find_page, only: [:show, :manage, :edit, :update, :destroy]
  http_basic_authenticate_with name: 'foo', password: 'bar', except: [:show, :home]

  # def show

  def manage
  end

  def new
    @page = Page.new
  end

  # def edit

  def create
    @page = Page.new(params[:page])

    if @page.save
      redirect_to manage_page_path(@page), notice: 'Page was successfully created.'
    else
      render action: :new
    end
  end

  def update
    if @page.update_attributes(params[:page])
      redirect_to manage_page_path(@page), notice: 'Page was successfully updated.'
    else
      render action: :edit
    end
  end

  def destroy
    @page.destroy

    redirect_to root_path
  end

  # TODO: Render, don't redirect.
  def home
    if Page.count == 0
      render text: 'Not Found', status: :not_found
    else
      redirect_to Page.first
    end
  end

  def sort
    Page.all.each do |page|
      page.position = params['page'].index(page.id.to_s)
      page.save
    end
    render nothing: true
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  http_basic_authenticate_with name: 'foo', password: 'bar'
  before_filter :find_page
  before_filter :find_section, only: [:show, :edit, :update, :destroy]

  # def show

  def new
    @section = @page.sections.build
    render layout: nil
  end

  # def edit

  def create
    @section = @page.sections.build(params[:section])

    if @section.save
      redirect_to manage_page_path(@page), notice: 'Section was successfully created.'
    else
      render action: :new
    end
  end

  def update
    if @section.update_attributes(params[:section])
      respond_to do |format|
        format.html { redirect_to manage_page_path(@page) }
        format.js { redirect_to [@page, @section], notice: 'Section was successfully updated.' }
      end
    else
      render action: :edit
    end
  end

  def destroy
    @section.destroy

    respond_to do |format|
      format.html { redirect_to @page, notice: 'Section was successfully destroyed.' }
      format.js { flash[:notice] = 'Section was successfully destroyed.' }
    end
  end

  def sort
    @page.sections.each do |section|
      section.position = params['section'].index(section.id.to_s)
      section.save
    end
    render nothing: true
  end

  private
  def find_section
    @section = @page.sections.find(params[:id])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page.title if @page %></title>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body<%== ' class="manage"' if controller.action_name == 'manage' or controller.controller_name == 'links' %>>
    
    <div id="notice">
      <%= flash[:notice] %>
    </div>

    <div id="header">
      <div>
        <%= link_to @site.title, root_url %>
        <span><%= @site.subtitle %></span>
      </div>
    </div>

    <div id="nav">
      <ol id="pages">
        <% Page.where(page_id: nil).each do |page| %>
          <%= content_tag :li, id: dom_id(page) do %>
            <% if controller.action_name == 'manage' or controller.controller_name == 'links' %>
              <%= link_to(page.title, manage_page_path(page)) %>
            <% else %>
              <%= link_to(page.title, page) %>
            <% end %>
            <% if page.pages.count > 0 %>
              <ol>
                <% page.pages.each do |subpage| %>
                  <% if controller.action_name == 'manage' or controller.controller_name == 'links' %>
                    <%= content_tag :li, link_to(subpage.title, manage_page_path(subpage)), id: dom_id(subpage) %>
                  <% else %>
                    <%= content_tag :li, link_to(subpage.title, subpage), id: dom_id(subpage) %>
                  <% end %>
                <% end %>
              </ol>
            <% end %>
          <% end %>
              
        <% end %>
      </ol>
      <% if controller.action_name == 'manage' or controller.controller_name == 'links' %>
        <ol>
          <li><%= link_to '+ Page', new_page_path, class: 'new' %></li>
        </ol>
      <% end %>
      <ol>
        <li>
          <span>Links</span>
          <ol id="links">
            <% @links.each do |link| %>
              <% if controller.action_name == 'manage' or controller.controller_name == 'links' %>
                <%= content_tag :li, link_to(link.title, edit_link_path(link), class: 'edit'), id: dom_id(link) %>
              <% else %>
                <%= content_tag :li, link_to(link.title, link.location), id: dom_id(link) %>
              <% end %>
            <% end %>
          </ol>
          <% if controller.action_name == 'manage' %>
            <ol>
              <li><%= link_to '+ Link', new_link_path, class: 'new' %></li>
            </ol>
          <% end %>
        </li>
      </ol>
      <div id="countdown">
        <% if @site.departs_on %>
          <%= (@site.departs_on - Date.today).to_i %> <%= @site.depart_text %>
        <% end %>
      </div>
    </div>

    <div id="content">
      <%= yield %>
    </div>

    <div id="footer">
      <% if controller.action_name == 'manage' or controller.controller_name == 'links' %>
        <%= link_to 'Log out', @page %>
      <% else %>
        <%= link_to 'Manage', manage_page_path(@page) %>
      <% end %>
    </div>

  </body>
</html>

app/views/layouts/application.js.erb
<%= yield %>
notice('<%= flash[:notice] %>');

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <ol class="fields">
    <li>
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: 'Title'  %>
    </li>
    <li>
      <%= f.label :location %>
      <%= f.text_field :location, placeholder: 'Location' %>
    </li>
  </ol>

  <ol class="actions">
    <li><%= f.submit %></li>
  </ol>
<% end %>

app/views/links/edit.js.erb
$('#<%= dom_id @link %>').html('<%=j render('form') %>');

app/views/links/new.html.erb
<div>
  <%= render 'form' %>
</div>

app/views/pages/_form.html.erb
<%# TODO: Remove the remote logic. %>
<%= form_for @page, remote: @page.new_record? ? false : true do |f| %>
  <ol class="fields">
    <% unless @page.new_record? %>
      <li>
        <%= f.label :page_id %>
        <%= f.collection_select :page_id, Page.where(page_id: nil).where("id != #{@page.id}").order(:position), :id, :title, :include_blank => true %>
      </li>
    <% end %>
    <li>
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: 'Title'  %>
    </li>
    <li>
      <%= f.label :text %>
      <%= f.text_area :text, placeholder: 'Text' %>
    </li>
    <li>
      <%= image_tag @page.image.url(:thumb) if @page.image? %>
      <%= f.label :image %>
      <%= f.file_field :image, class: @page.image? ? :hidden : nil  %>
    </li>
  </ol>

  <ol class="actions">
    <li><%= f.submit %></li>
  </ol>
<% end %>

app/views/pages/_page.html.erb
<div data-page="<%= @page.to_param %>"<%== ' class="show"' if controller.action_name == 'show' %>>
  <%= link_to '', edit_page_path(page), class: 'edit' if controller.action_name == 'manage' %>
  <h1><%= page.title %></h1>
  <%= image_tag page.image.url(:small) if page.image? %>
  <%== page.text %>
</div>

app/views/pages/edit.html.erb
<div>
  <%= render 'form' %>
</div>

app/views/pages/edit.js.erb
$('[data-page]').html('<%=j render('form') %>');
bindNotice('form[data-remote]', 'Saving ...');
$('form img').click(function() {
  $(this).siblings('input[type=file]').click();
});
$('textarea').tinymce({
  content_css: '/assets/content.css',
  theme: 'advanced',
  theme_advanced_buttons1: 'bold,italic,strikethrough,separator,bullist,numlist,separator,undo,redo,separator,link,unlink',
  theme_advanced_buttons2: '',
  theme_advanced_buttons3: ''
});

app/views/pages/manage.html.erb
<%= render @page %>

<div id="sections">
  <%= render @page.sections %>
</div>

<div id="new_section">
  <%= link_to '+ Section', new_page_section_path(@page), class: 'new' %>
</div>

<%# TODO: Add dynamic 'page updated at' information. %>

app/views/pages/manage.js.erb
$('[data-page]').replaceWith('<%=j render(@page) %>');
bindAJAX('[data-page] a.edit');

app/views/pages/show.html.erb
<%= render @page %>

<div id="sections">
  <%= render @page.sections %>
</div>

<div id="new_section">
  <%= link_to '+ Section', new_page_section_path(@page), class: 'new' %>
</div>

<%# TODO: Add dynamic 'page updated at' information. %>

app/views/pages/show.js.erb
$('[data-page]').replaceWith('<%=j render(@page) %>');
bindAJAX('[data-page] a.edit');

app/views/sections/_form.html.erb
<%# TODO: Remove the remote logic. %>
<%= form_for [@page, @section], remote: @section.new_record? ? false : true do |f| %>
  <ol class="fields">
    <li>
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: 'Title' %>
    </li>
    <li>
      <%= f.label :text %>
      <%= f.text_area :text, placeholder: 'Text' %>
    </li>
    <li>
      <%= image_tag @section.section_image.url(:thumb) if @section.section_image? %>
      <%= f.label :section_image %>
      <%= f.file_field :section_image, class: @section.section_image? ? :hidden : nil  %>
    </li>
  </ol>

  <ol class="actions">
    <li><%= f.submit %></li>
  </ol>
<% end %>

app/views/sections/_section.html.erb
<div id="<%= dom_id section %>" data-section="<%= section.to_param %>"<%== ' class="show"' if controller.action_name == 'show' %>>
  <%= link_to '', edit_page_section_path(@page, section), class: 'edit' if controller.action_name == 'manage' or controller.controller_name == 'sections' %>
  <%= link_to "\u2716", page_section_path(@page, section), method: 'delete', class: 'delete', confirm: 'Delete section?' if controller.action_name == 'manage' or controller.controller_name == 'sections' %>
  <%= content_tag :h2, section.title unless section.title.blank? %>
  <%= image_tag section.section_image.url(:small) if section.section_image? %>
  <%== section.text %>
</div>

app/views/sections/destroy.js.erb
$('#section_<%= @section.to_param %>').remove();

app/views/sections/edit.html.erb
<%= render 'form' %>

app/views/sections/edit.js.erb
$('#<%= dom_id @section %>').html('<%=j render('form') %>');
bindNotice('form[data-remote]', 'Saving ...');
$('form img').click(function() {
  $(this).siblings('input[type=file]').click();
});
$('textarea').tinymce({
  content_css: '/assets/content.css',
  theme: 'advanced',
  theme_advanced_buttons1: 'bold,italic,strikethrough,separator,bullist,numlist,separator,undo,redo,separator,link,unlink',
  theme_advanced_buttons2: '',
  theme_advanced_buttons3: ''
});

app/views/sections/new.html.erb
<%= render 'form' %>

app/views/sections/new.js.erb
$('#new_section').html('<%=j render('form') %>');

app/views/sections/show.js.erb
$('#<%= dom_id @section %>').replaceWith('<%=j render(@section) %>');
bindAJAX('#<%= dom_id @section %> a.edit');